export const S = {
  // ── LAYOUT
  root: { fontFamily: "'Nunito', 'Segoe UI', Tahoma, Arial, sans-serif", background: "#F0F4F8", minHeight: "100vh", display: "flex", flexDirection: "column" },
  topBar: { background: "linear-gradient(135deg, #1B3A5C 0%, #1B5C8A 100%)", color: "#fff", position: "sticky", top: 0, zIndex: 100, boxShadow: "0 2px 16px rgba(0,0,0,0.25)" },
  topBarInner: { maxWidth: 960, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 20px", gap: 12, flexWrap: "wrap" },
  logoBox: { display: "flex", alignItems: "center", gap: 10 },
  logoCircle: { width: 40, height: 40, borderRadius: "50%", background: "rgba(255,255,255,0.15)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, flexShrink: 0 },
  logoText: { lineHeight: 1.25 },
  logoName: { fontSize: 15, fontWeight: 800, letterSpacing: 0.3 },
  logoTagline: { fontSize: 10, opacity: 0.75, fontWeight: 400 },
  navTabs: { display: "flex", background: "rgba(0,0,0,0.2)", borderRadius: 10, overflow: "hidden", flexWrap: "wrap" },
  navTab: { padding: "7px 13px", fontSize: 12, fontWeight: 700, cursor: "pointer", border: "none", background: "transparent", color: "rgba(255,255,255,0.65)", transition: "all 0.18s", letterSpacing: 0.3, fontFamily: "'Nunito', sans-serif" },
  navTabActive: { background: "rgba(255,255,255,0.22)", color: "#fff" },
  languageToggle: { background: "rgba(255,255,255,0.12)", color: "#fff", borderLeft: "1px solid rgba(255,255,255,0.12)" },
  body: { maxWidth: 960, margin: "0 auto", width: "100%", padding: "18px 16px", flex: 1 },

  // ── HOME
  heroBanner: { background: "linear-gradient(135deg, #1B3A5C, #1B5C8A)", borderRadius: 18, padding: "24px 26px", color: "#fff", marginBottom: 16, overflow: "hidden", position: "relative" },
  heroEyebrow: { fontSize: 10, opacity: 0.7, marginBottom: 5, letterSpacing: 1.2, textTransform: "uppercase" },
  heroTitle: { fontSize: 22, fontWeight: 800, marginBottom: 6 },
  heroSub: { fontSize: 13, opacity: 0.85, lineHeight: 1.6, maxWidth: 520 },
  heroStats: { display: "flex", gap: 28, marginTop: 18, flexWrap: "wrap" },
  heroStat: { textAlign: "center" },
  heroStatNum: { fontSize: 24, fontWeight: 800 },
  heroStatLabel: { fontSize: 10, opacity: 0.72, marginTop: 2 },
  alertCard: { background: "#fff", borderRadius: 12, padding: "13px 16px", marginBottom: 10, display: "flex", alignItems: "center", gap: 12, boxShadow: "0 1px 5px rgba(0,0,0,0.07)" },
  alertDot: { width: 9, height: 9, borderRadius: "50%", flexShrink: 0 },
  alertText: { flex: 1, fontSize: 13, color: "#1B3A5C", lineHeight: 1.4 },
  alertAction: { fontSize: 11, color: "#1B5C8A", fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" },
  sectionTitle: { fontSize: 11, fontWeight: 800, color: "#8A9BB0", marginBottom: 10, marginTop: 6, letterSpacing: 1.2, textTransform: "uppercase" },
  quickGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 10, marginBottom: 18 },
  quickCard: { background: "#fff", borderRadius: 14, padding: "16px 14px", cursor: "pointer", transition: "transform 0.15s, box-shadow 0.15s", boxShadow: "0 1px 5px rgba(0,0,0,0.06)" },
  quickCardIcon: { fontSize: 26, marginBottom: 10 },
  quickCardLabel: { fontSize: 13, fontWeight: 800, color: "#1B3A5C", marginBottom: 3 },
  quickCardSub: { fontSize: 11, color: "#8A9BB0" },

  // ── TESTS LIST
  searchWrap: { position: "relative", marginBottom: 10 },
  searchInput: { width: "100%", padding: "10px 16px 10px 42px", borderRadius: 12, border: "1.5px solid #DDE3EC", fontSize: 13, background: "#fff", color: "#1B3A5C", outline: "none", fontFamily: "'Nunito', sans-serif", boxSizing: "border-box" },
  searchIcon: { position: "absolute", left: 13, top: "50%", transform: "translateY(-50%)", fontSize: 16, color: "#A0AABB", pointerEvents: "none" },
  pillRow: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 14 },
  pill: { padding: "5px 13px", borderRadius: 20, fontSize: 11, fontWeight: 700, cursor: "pointer", border: "1.5px solid #DDE3EC", background: "#fff", color: "#8A9BB0", whiteSpace: "nowrap", transition: "all 0.15s", fontFamily: "'Nunito', sans-serif" },
  pillActive: { background: "#1B5C8A", color: "#fff", borderColor: "#1B5C8A" },
  catHeader: { fontSize: 11, fontWeight: 800, letterSpacing: 0.6, textTransform: "uppercase", marginBottom: 8, display: "flex", alignItems: "center", gap: 6 },
  catCount: { borderRadius: 20, padding: "1px 8px", fontSize: 10, fontWeight: 700 },
  testCard: { background: "#fff", borderRadius: 12, padding: "12px 14px", marginBottom: 8, display: "flex", gap: 12, cursor: "pointer", boxShadow: "0 1px 4px rgba(0,0,0,0.06)", transition: "transform 0.12s, box-shadow 0.12s", alignItems: "flex-start" },
  testIconBox: { width: 40, height: 40, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, flexShrink: 0 },
  testMeta: { flex: 1, minWidth: 0 },
  testName: { fontSize: 13, fontWeight: 700, color: "#1B3A5C", marginBottom: 3, lineHeight: 1.4 },
  testDesc: { fontSize: 11, color: "#8A9BB0", lineHeight: 1.5 },
  exclusiveBadge: { fontSize: 9, padding: "3px 7px", borderRadius: 20, background: "#FFF3E0", color: "#BF360C", fontWeight: 800, whiteSpace: "nowrap", alignSelf: "flex-start", marginTop: 2, letterSpacing: 0.3, border: "1px solid #FFE0B2" },

  // ── TEST DETAIL
  detailBack: { display: "inline-flex", alignItems: "center", gap: 5, cursor: "pointer", fontSize: 13, color: "#1B5C8A", fontWeight: 700, marginBottom: 14, padding: "6px 12px", borderRadius: 8, background: "#E8F1FA" },
  detailCard: { background: "#fff", borderRadius: 18, overflow: "hidden", boxShadow: "0 3px 16px rgba(0,0,0,0.09)" },
  detailHeaderBase: { padding: "22px 22px 18px", color: "#fff" },
  detailEyebrow: { fontSize: 10, opacity: 0.8, marginBottom: 5, textTransform: "uppercase", letterSpacing: 1 },
  detailTitle: { fontSize: 19, fontWeight: 800, marginBottom: 5, lineHeight: 1.3 },
  detailSub: { fontSize: 12, opacity: 0.85 },
  detailBody: { padding: "18px 22px" },
  infoBlock: { marginBottom: 18, paddingBottom: 16, borderBottom: "1px solid #F0F4F8" },
  infoBlockLast: { marginBottom: 0 },
  infoLabel: { fontSize: 10, fontWeight: 800, color: "#A0AABB", textTransform: "uppercase", letterSpacing: 0.9, marginBottom: 7 },
  infoPara: { fontSize: 13, color: "#3A4A5C", lineHeight: 1.75 },
  sampleChip: { display: "inline-block", background: "#F0F4F8", color: "#1B3A5C", fontSize: 12, fontWeight: 700, padding: "5px 12px", borderRadius: 20, marginTop: 4 },
  exclusiveBlock: { background: "#FFF8F0", border: "1.5px solid #FFD5B0", borderRadius: 10, padding: "10px 14px", marginTop: 12, fontSize: 12, color: "#8B3000", fontWeight: 600 },
  askBtn: { width: "100%", padding: "13px", background: "linear-gradient(135deg, #1B3A5C, #1B5C8A)", color: "#fff", border: "none", borderRadius: 12, fontSize: 13, fontWeight: 700, cursor: "pointer", marginTop: 16, fontFamily: "'Nunito', sans-serif", letterSpacing: 0.3 },

  // ── CHAT
  chatItemBox: { background: "#fff", borderRadius: 12, padding: "12px 15px", marginBottom: 8, display: "flex", gap: 12, cursor: "pointer", boxShadow: "0 1px 5px rgba(0,0,0,0.06)", alignItems: "center", transition: "box-shadow 0.15s" },
  avatar: { width: 44, height: 44, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 800, flexShrink: 0 },
  chatName: { fontSize: 13, fontWeight: 800, color: "#1B3A5C", marginBottom: 2 },
  chatPreview: { fontSize: 11, color: "#8A9BB0", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 220 },
  chatTime: { fontSize: 10, color: "#C0C8D0" },
  unreadDot: { width: 9, height: 9, borderRadius: "50%", background: "#1B5C8A", flexShrink: 0 },
  chatWindowWrap: { display: "flex", flexDirection: "column", height: "calc(100vh - 180px)", minHeight: 400 },
  chatMsgsArea: { flex: 1, overflowY: "auto", background: "#F5F8FC", borderRadius: 14, padding: "14px", display: "flex", flexDirection: "column", gap: 10 },
  msgWrap: { display: "flex", flexDirection: "column" },
  msgMe: { alignSelf: "flex-end", maxWidth: "74%" },
  msgThem: { alignSelf: "flex-start", maxWidth: "74%" },
  bubbleMe: { background: "linear-gradient(135deg, #1B3A5C, #1B5C8A)", color: "#fff", padding: "10px 14px", borderRadius: "14px 4px 14px 14px", fontSize: 13, lineHeight: 1.55 },
  bubbleThem: { background: "#fff", color: "#1B3A5C", padding: "10px 14px", borderRadius: "4px 14px 14px 14px", fontSize: 13, lineHeight: 1.55, boxShadow: "0 1px 4px rgba(0,0,0,0.07)" },
  msgTime: { fontSize: 10, color: "#B0BAC8", marginTop: 4, textAlign: "right" },
  chatInputRow: { display: "flex", gap: 8, paddingTop: 12, alignItems: "center" },
  chatInput: { flex: 1, border: "1.5px solid #DDE3EC", borderRadius: 26, padding: "10px 16px", fontSize: 13, color: "#1B3A5C", background: "#fff", outline: "none", fontFamily: "'Nunito', sans-serif" },
  sendBtn: { width: 42, height: 42, borderRadius: "50%", background: "linear-gradient(135deg, #1B3A5C, #1B5C8A)", border: "none", color: "#fff", fontSize: 15, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },

  // ── REPORTS
  reportCard: { background: "#fff", borderRadius: 14, padding: "15px 17px", marginBottom: 10, boxShadow: "0 1px 5px rgba(0,0,0,0.07)" },
  reportTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6, gap: 8 },
  reportName: { fontSize: 14, fontWeight: 800, color: "#1B3A5C", lineHeight: 1.3 },
  statusReady: { fontSize: 10, padding: "4px 10px", borderRadius: 20, background: "#E8F5E9", color: "#1B5E20", fontWeight: 800, whiteSpace: "nowrap" },
  statusPending: { fontSize: 10, padding: "4px 10px", borderRadius: 20, background: "#FFF8E1", color: "#E65100", fontWeight: 800, whiteSpace: "nowrap" },
  reportDate: { fontSize: 11, color: "#8A9BB0", marginBottom: 2 },
  reportId: { fontSize: 10, color: "#C0C8D0", fontFamily: "monospace" },
  reportBtns: { display: "flex", gap: 8, marginTop: 13 },
  btnSecondary: { flex: 1, padding: "9px", borderRadius: 9, border: "1.5px solid #DDE3EC", background: "#F8FAFC", color: "#1B3A5C", fontSize: 12, fontWeight: 700, cursor: "pointer", textAlign: "center", fontFamily: "'Nunito', sans-serif" },
  btnPrimary: { flex: 1, padding: "9px", borderRadius: 9, border: "none", background: "linear-gradient(135deg, #1B3A5C, #1B5C8A)", color: "#fff", fontSize: 12, fontWeight: 700, cursor: "pointer", textAlign: "center", fontFamily: "'Nunito', sans-serif" },
  resultTable: { width: "100%", borderCollapse: "collapse", marginTop: 14, fontSize: 12 },
  resultTh: { textAlign: "left", padding: "8px 10px", background: "#F0F4F8", color: "#6A7A8C", fontWeight: 800, fontSize: 11, letterSpacing: 0.4 },
  resultTd: { padding: "8px 10px", borderBottom: "1px solid #F5F8FC", color: "#2C3E50" },
  resultHigh: { color: "#C0392B", fontWeight: 800 },
  resultLow: { color: "#2471A3", fontWeight: 800 },
  interpretNote: { marginTop: 14, padding: "12px 14px", background: "#FFFBF0", borderRadius: 10, fontSize: 12, color: "#856404", border: "1px solid #FFE8A0", lineHeight: 1.6 },
  pdfFrame: { width: "100%", minHeight: 520, border: "1px solid #DDE3EC", borderRadius: 12, background: "#F8FAFC" },

  // ── ABOUT
  aboutHeaderCard: { background: "linear-gradient(135deg, #1B3A5C, #1B5C8A)", borderRadius: 18, padding: "24px", color: "#fff", marginBottom: 14 },
  aboutCard: { background: "#fff", borderRadius: 14, padding: "18px 20px", marginBottom: 12, boxShadow: "0 1px 5px rgba(0,0,0,0.06)" },
  directorRow: { display: "flex", alignItems: "center", gap: 14, marginTop: 16 },
  directorAvatar: { width: 58, height: 58, borderRadius: "50%", background: "rgba(255,255,255,0.18)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 24, flexShrink: 0 },
  directorName: { fontSize: 16, fontWeight: 800 },
  directorCred: { fontSize: 11, opacity: 0.82, marginTop: 3 },
  contactRow: { display: "flex", alignItems: "center", gap: 12, padding: "11px 0", borderBottom: "1px solid #F0F4F8", fontSize: 13, color: "#3A4A5C" },
  deptTag: { padding: "5px 12px", borderRadius: 20, fontSize: 11, fontWeight: 700, cursor: "pointer", marginBottom: 4 },

  // ── PROFILE
  profileHero: { background: "linear-gradient(135deg, #1B3A5C, #1B5C8A)", borderRadius: 18, padding: "28px", color: "#fff", textAlign: "center", marginBottom: 16 },
  profileAvatarBox: { width: 68, height: 68, borderRadius: "50%", background: "rgba(255,255,255,0.2)", margin: "0 auto 12px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28, fontWeight: 800 },
  menuCard: { background: "#fff", borderRadius: 14, overflow: "hidden", marginBottom: 10, boxShadow: "0 1px 5px rgba(0,0,0,0.06)" },
  menuRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 18px", borderBottom: "1px solid #F8FAFC", fontSize: 13, color: "#1B3A5C", cursor: "pointer" },
  menuLeft: { display: "flex", gap: 12, alignItems: "center" },

  // BOOKING
  bookingLayout: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14, alignItems: "start" },
  bookingForm: { background: "#fff", borderRadius: 14, padding: "18px", boxShadow: "0 1px 5px rgba(0,0,0,0.06)" },
  bookingHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 16 },
  bookingTitle: { fontSize: 15, fontWeight: 800, color: "#1B3A5C", marginBottom: 3 },
  bookingSubtitle: { fontSize: 12, color: "#8A9BB0", lineHeight: 1.5 },
  bookingCount: { minWidth: 38, height: 38, borderRadius: 10, background: "#E8F1FA", color: "#1B5C8A", fontSize: 16, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center" },
  formLabel: { display: "block", fontSize: 11, fontWeight: 800, color: "#6A7A8C", textTransform: "uppercase", letterSpacing: 0.7, marginBottom: 6, marginTop: 12 },
  formInput: { width: "100%", border: "1.5px solid #DDE3EC", borderRadius: 10, padding: "10px 12px", fontSize: 13, color: "#1B3A5C", background: "#fff", outline: "none", boxSizing: "border-box", fontFamily: "'Nunito', sans-serif" },
  formTextarea: { minHeight: 96, resize: "vertical", lineHeight: 1.5 },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 10 },
  formMessage: { marginTop: 12, padding: "10px 12px", borderRadius: 10, background: "#E8F5E9", color: "#1B5E20", fontSize: 12, fontWeight: 700 },
  bookingSubmit: { width: "100%", marginTop: 14, flex: "none" },
  bookingList: { background: "#fff", borderRadius: 14, padding: "18px", boxShadow: "0 1px 5px rgba(0,0,0,0.06)" },
  emptyBooking: { textAlign: "center", padding: "34px 10px", borderRadius: 12, background: "#F8FAFC", marginTop: 14 },
  bookingCard: { border: "1px solid #EEF2F7", borderRadius: 12, padding: "12px", marginTop: 12, background: "#FBFCFE" },
  bookingCardTop: { display: "flex", justifyContent: "space-between", gap: 10, alignItems: "flex-start" },
  bookingPatient: { fontSize: 14, fontWeight: 800, color: "#1B3A5C", lineHeight: 1.3 },
  bookingRef: { fontSize: 10, color: "#A0AABB", marginTop: 2 },
  bookingComplaint: { marginTop: 10, fontSize: 13, color: "#3A4A5C", lineHeight: 1.6 },
  bookingMetaRow: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 10 },
  smallDangerBtn: { border: "1px solid #F2C7C7", background: "#FFF5F5", color: "#C0392B", borderRadius: 8, padding: "5px 9px", fontSize: 11, fontWeight: 800, cursor: "pointer", fontFamily: "'Nunito', sans-serif" },

  // CLINIC PHONE
  clinicHero: { background: "linear-gradient(135deg, #12314F, #1B5C8A)", borderRadius: 18, padding: "22px", color: "#fff", marginBottom: 14, display: "flex", justifyContent: "space-between", gap: 16, alignItems: "flex-start", flexWrap: "wrap" },
  clinicEyebrow: { fontSize: 10, opacity: 0.72, textTransform: "uppercase", letterSpacing: 1.1, marginBottom: 6 },
  clinicTitle: { fontSize: 21, fontWeight: 800, marginBottom: 6 },
  clinicSubtitle: { fontSize: 13, opacity: 0.85, lineHeight: 1.55, maxWidth: 560 },
  clinicStats: { display: "flex", gap: 10, flexWrap: "wrap" },
  clinicStatsItem: { minWidth: 82, borderRadius: 12, background: "rgba(255,255,255,0.14)", padding: "10px 12px", textAlign: "center", display: "grid", gap: 2 },
  clinicList: { display: "grid", gap: 10 },
  clinicPatientCard: { background: "#fff", borderRadius: 14, padding: "14px", boxShadow: "0 1px 5px rgba(0,0,0,0.07)" },
  clinicCardTop: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-start" },
  clinicTimeBox: { minWidth: 92, borderRadius: 12, background: "#E8F1FA", color: "#1B5C8A", padding: "8px 10px", textAlign: "center" },
  clinicComplaint: { marginTop: 12, padding: "10px 12px", borderRadius: 10, background: "#F8FAFC", color: "#3A4A5C", fontSize: 13, lineHeight: 1.55 },
  clinicPhoneRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap", marginTop: 10, fontSize: 13, color: "#1B3A5C", fontWeight: 700 },
  callButton: { textDecoration: "none", borderRadius: 20, background: "#E8F5E9", color: "#1B5E20", padding: "6px 12px", fontSize: 12, fontWeight: 800 },
  clinicActions: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))", gap: 8, marginTop: 12, alignItems: "stretch" },
  clinicStatus: { marginTop: 9, fontSize: 11, color: "#8A9BB0", fontWeight: 800 },
  baseResultBox: { marginTop: 12, padding: "12px", borderRadius: 12, background: "#F8FAFC", border: "1px solid #EEF2F7" },

  // AUTH
  authPage: { minHeight: "100vh", background: "linear-gradient(135deg, #E8F1FA, #F7FAFC)", display: "flex", alignItems: "center", justifyContent: "center", padding: 18, fontFamily: "'Nunito', 'Segoe UI', Tahoma, Arial, sans-serif" },
  authCard: { width: "100%", maxWidth: 430, background: "#fff", borderRadius: 18, padding: "24px", boxShadow: "0 16px 50px rgba(27,58,92,0.18)" },
  authTitle: { fontSize: 22, fontWeight: 800, color: "#1B3A5C", marginTop: 14, marginBottom: 6 },
  authSubtitle: { fontSize: 13, color: "#6A7A8C", lineHeight: 1.6, marginBottom: 16 },
  authProviderGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 8, marginBottom: 14 },
  authProviderBtn: { width: "100%", border: "1.5px solid #DDE3EC", background: "#F8FAFC", color: "#1B3A5C", borderRadius: 12, padding: "11px 14px", fontSize: 13, fontWeight: 800, cursor: "pointer", textAlign: "center", fontFamily: "'Nunito', sans-serif" },
  authDivider: { textAlign: "center", color: "#A0AABB", fontSize: 11, fontWeight: 800, textTransform: "uppercase", letterSpacing: 1, margin: "12px 0 4px" },
  authNote: { marginTop: 14, color: "#8A9BB0", fontSize: 11, lineHeight: 1.6 },
};
